on : push
jobs : 
      first-job:
          runs-on : windows-latest
          steps : 
                - run : node --version      
                - uses : actions/checkout@v3  
                - run : npx eslint index.js 
                - run : npm start   